### ISSUE TITLE
[FEATURE REQUEST] Load multiple ads up front

### ISSUE THREAD

**Issue by FuseGamesLLC** [YoYoGames/GMEXT-AdMob#19]
I noticed in the Google Documentation they allow for multiple ads of the same type to be loaded up front (for a waterfall type ad menu that allows users to watch multiple ads back to back). It would be great to have this feature in an upcoming update.

**Comment by DiasFranciscoA** [comment]
Implemented in main branch waiting for documentation

**Comment by YYBartT** [comment]
Documented the new functions and modified the descriptions of existing functions.
