### ISSUE TITLE
AdMob ad unit IDs get wiped from the source when creating iOS build

### ISSUE THREAD

**Issue by aliustaoglu** [YoYoGames/GMEXT-AdMob#2]
I am using the official AdMob extension. It works alright however some minor issues. First of all ad unit IDs that I put in the extension are not used at all. "GoogleMobileAdsGM.mm" file contains empty values which I would expect to be filled from the extension options when I create an iOS build. I have to enter these values manually in the native code. And also whenever I create a new build, these values are wiped and I have to repeat this process.

<img width="498" alt="image" src="https://user-images.githubusercontent.com/15793376/233813321-cf3fe4af-1235-44d6-9d33-0bce4207f7af.png">

Android build however works fine and expectedly puts ad unit values in the native Java files so it's always synced to GameMaker extension options. I would expect iOS export would work the same.

Workaround is to edit these values manually but a permanent solution would be good. I was reporting this on YoyoGames' report a bug section, but it was suggested that I should report it here.

**Comment by DiasFranciscoA** [comment]
<img width="1755" alt="image" src="https://user-images.githubusercontent.com/85873067/234300635-5edd5dd4-9e6f-494d-885a-29c22d243a2e.png">

Upon reviewing the code, we couldn't identify any difference between the way the iOS and Android versions work. However, if Android is placing the values inside the native Java files, we should investigate this matter. Can you please direct us to the specific location within the Java native code where this is happening?

**Comment by DiasFranciscoA** [comment]
Can you please confirm if this is still an issue?

**Comment by aliustaoglu** [comment]
Hey, sorry forgot to return to this. I made a release the other day and I can confirm it works for me. Both Android and iOS versions work. This could be closed.
