### ISSUE TITLE
[UPDATE REQUEST] - To the 22.6.0

### ISSUE THREAD

**Issue by Callsign54** [YoYoGames/GMEXT-AdMob#22]
The current GMEXT's AdMob version will be in depreciation in Q1 - 2024. Could you please update the extension to the current AdMob version?

**Comment by GravityBongInSpace** [comment]
Where did you find this out?

**Comment by Callsign54** [comment]
> Where did you find this out?

My apologizes. I forgot to include the source.
[AdMob SDK Timetable](https://developers.google.com/admob/android/deprecation)
[GMExt-AdMob version of AdMob SDK](https://github.com/YoYoGames/GMEXT-AdMob/blob/4975a4a02f782fc60ea78aaf38236a87abd58682/source/AdMob_gml/extensions/admob/AdMob.yy#L7C3-L7C3) as it uses 21.3.0

AdMob SDK will not stop working in depreciation date, but I believe anything is possible since this is Google ^^

**Comment by DiasFranciscoA** [comment]
This issue is now solved with version v1.3.4
