### ISSUE TITLE
Which Ide works with the current AdMob EXT?

### ISSUE THREAD

**Issue by GravityBongInSpace** [YoYoGames/GMEXT-AdMob#23]
I can't find one that works, every time I enable Ad mob the build fails , I've tried many different IDE

**Comment by DiasFranciscoA** [comment]
Hello @GravityBongInSpace in order to help you with your issue we will need to know what is the reason of the failure, specially what are the output logs.

**Comment by GravityBongInSpace** [comment]
I got it to work , my minimum sdk was set too low , I raised it from 16 to 19 and it worked
