### ISSUE TITLE
[BUG] AdMob_Banner_Set_AdUnit is not present in the GMExt

### ISSUE THREAD

**Issue by Callsign54** [YoYoGames/GMEXT-AdMob#28]
You forgot to include the function in the Extension Settings, but it's present in the .java file.

**Comment by Callsign54** [comment]
Just realised that you left out the "AdMob_<ad_type>_Init" functions in the extension, though these are not present in the Android/iOS extensions' source code, and should be removed.

**Comment by DiasFranciscoA** [comment]
> r

They should not be removed to allow compatibility with the older version of the extension since they do the same. It was just a renaming, in the extension file they map to the new AdMob_<ad_type>_Set_AdUnit functions.

**Comment by DiasFranciscoA** [comment]
Fixed on hotfix 1.3.1
