### ISSUE TITLE
[SUGGESTION] Insufficient macros for the AdMob_OnPaidEvent

### ISSUE THREAD

**Issue by Callsign54** [YoYoGames/GMEXT-AdMob#29]
Currently, the "precision" key returned in the async event (see async_load[? "precision"]) is a numeric value. Originally, as in the Google's documents, it's actually a constant that represents the type of the paid ad event. (See the documentation [here](https://developers.google.com/android/reference/com/google/android/gms/ads/AdValue.PrecisionType))

**Suggestion**
To include ESTIMATED, PRECISE, PUBLISHER_PROVIDED and UNKNOWN macros.

**Comment by DiasFranciscoA** [comment]
Fixed on v1.3.1 hotfix
