### ISSUE TITLE
[PENDING] Google Play bundle tool error

### ISSUE THREAD

**Issue by djscuba** [YoYoGames/GMEXT-AdMob#3]
It seems the admob extension is the root of an error when uploading to Google Play: 

An error occurred while running bundletool build-apks on your uploaded App Bundle. Ensure that your App Bundle is valid by running bundletool build-apks locally and try again.

The AAB complies perfectly but the error happens when uploading to Google Play. The error does not appear when the extension is disabled.

**Comment by DiasFranciscoA** [comment]
Thank you for reaching out to us regarding the issue you encountered while uploading your App Bundle to Google Play. We understand that you are experiencing an error message related to the admob extension.

We have thoroughly investigated this matter, and unfortunately, we were unable to reproduce the error in our local environment. However, we would like to assist you further by examining your project directly.

To facilitate a more in-depth analysis, we kindly request that you provide us with your project files (YYZ and also if possible send us the compiled AAB). Please do so using our HelpDesk ticket system.
