### ISSUE TITLE
Property 'nonPersonalizedAds' not found on object of type 'GoogleMobileAdsGM

### ISSUE THREAD

**Issue by Schwarzgamescom** [YoYoGames/GMEXT-AdMob#30]
Hello, I'm using XCode 15.1, Gamemaker 2023.11.1.129 and Admob Extension 1.3.1.

Besides other issues I get this one in XCode. 

![image](https://github.com/YoYoGames/GMEXT-AdMob/assets/145435972/38b826d3-b9a1-411e-afa9-24f1a72e780f)

Looks like something is wrong with this one item 'nonPersonalizedAds'. Does it have to do with the AdMob_NonPersonalizedAds_Set function in the extension?

I'm far from understanding this issue output, but the other issues could be related to this one.

When the admob extension is deactivated, the app works fine.

**Comment by Schwarzgamescom** [comment]
When I use Admob Extension 1.2.3 there are no errors and test ads show up as intended.

**Comment by DiasFranciscoA** [comment]
Setting nonPersonalizedAds doesn't do anything at all to be honest so you should be able to safely remove that line that was a type that stayed there from prev implementation we will be fixing it ASAP

**Comment by Schwarzgamescom** [comment]
After deleting that line all the other issues remained. Three of them can be seen in detail in the above screenshot.
Should I send more details for the other issues?

**Comment by DiasFranciscoA** [comment]
> After deleting that line all the other issues remained. Three of them can be seen in detail in the above screenshot. Should I send more details for the other issues?

Noticed that too as soon as started fixing the prev issue (there was some code that got moved around I required some changes to the .h file too)

Fixed the issues and made a new Publish of the extension... 1.3.2 (both on github and marketplace) this issue will be closed.

**Comment by Schwarzgamescom** [comment]
Thanks for the quick fix, now the app works and test ads show up, but my bottom banner ad now appears at the top of the screen, even though bottom is true and I didn't change anything in my code.
