### ISSUE TITLE
java.lang.StackOverflowError (no error message)

### ISSUE THREAD

**Issue by IsanagiGames** [YoYoGames/GMEXT-AdMob#31]
I'm using the Google Admob extension GMS2.3 - Version 1.3.2 and even in blank projects I'm getting this error "java.lang.StackOverflowError (no error message)" 
What am I doing wrong? I'm using Game maker Studio version 2.3 that the extension says. :c

**Comment by DiasFranciscoA** [comment]
We just released a new hotfix that fixes a compilation problem on Android (hotfix 1.3.3)
