### ISSUE TITLE
Error when running build in empty project

### ISSUE THREAD

**Issue by samuelrl86** [YoYoGames/GMEXT-AdMob#32]
I am trying to use the newest version of Google Admob and when I run directly after importing the AdMob extension I receive an error with build failure. I am using IDE v2023.4.0.84 Runtime v2023.4.0.113 . The error shows when I am running try to run the project from a new project file as well. Thank you,
-Sam

![build failure with AdMob extension](https://github.com/YoYoGames/GMEXT-AdMob/assets/46635589/479b0243-fad6-477e-984d-e0a4a561392d)

> Task :com.company.game:compileDebugJavaWithJavac FAILED
C:\Users\Sam\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\Mobile_Gam_E5DBE4E6_DDFB8925\Android\Default\com.company.game\src\main\java\com\company\game\GoogleMobileAdsGM.java:1352: error: cannot find symbol
builder.setRequestAgent("gmext-admob-" + RunnerJNILib.extGetVersion("AdMob"));
^
symbol: method extGetVersion(String)
location: class RunnerJNILib
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.

**Comment by samuelrl86** [comment]
More Info about the issue, entire build output.
[build failure with AdMob extension.txt](https://github.com/YoYoGames/GMEXT-AdMob/files/13924072/build.failure.with.AdMob.extension.txt)

**Comment by DiasFranciscoA** [comment]
Please check the release notes for compatible IDE and runtime versions.

https://github.com/YoYoGames/GMEXT-AdMob/releases

This extension requires 2023.11 or later.
