### ISSUE TITLE
Important increase in Megabytes in new Admob extension Version

### ISSUE THREAD

**Issue by Manuvkas** [YoYoGames/GMEXT-AdMob#33]
In the latest version of the admob extension (1.3.3), 2 MB has been increased when generating a bundle. In version 1.3.1 the bundles took up 2 MB less.

This increase does not seem to be justified and greatly affects Google Play statistics, please keep this in mind.

Could you please check if this is an error or explain to us why the new extension should take up two more megabytes?

For your information, I do not use any mediation extension, only Admob.

Thank you

**Comment by jzavala-YYG** [comment]
@Manuvkas Last update **_com.google.android.gms:play-services-ads_** was updated from to 21.3.0 -> 22.6.0

**Comment by Manuvkas** [comment]
Thank you!!
