### ISSUE TITLE
Build failed! - can not complete the build every time

### ISSUE THREAD

**Issue by MitashkiHub** [YoYoGames/GMEXT-AdMob#34]
GameMaker Studio IDE - v2023.11.1.129 Runtime v2023.11.1.160
Android Studio 
API: 2022.1.1 Patch 1 (Electric Eel)

Everytime when I add the extension to the game for test it can not complete the build. I tryed by make a whole new project only with the Demo, but I'm get the exact same error. Without the extension the GameMaker compiles my game just fines.

Output:
![Екранна снимка 2024-02-07 005847](https://github.com/YoYoGames/GMEXT-AdMob/assets/159200642/cfa1882d-a8fd-4519-9f42-8526457ef5ba)

**Comment by DiasFranciscoA** [comment]
Thank you for reaching out to us, looking at your error report:

<img width="1383" alt="image" src="https://github.com/YoYoGames/GMEXT-AdMob/assets/85873067/d985d93e-c488-42ec-9c23-b072caafafe6">

You can check that the reason and the solution are both there, the Android SDK you are targeting is SDK v16 but it should be at least SDK v19. This option can be changed using `Game Options -> Android`

<img width="608" alt="image" src="https://github.com/YoYoGames/GMEXT-AdMob/assets/85873067/07b6295f-c50c-4cb1-ba3c-4fd5c4d211ef">

Change the above 16 into at least 19.
Let us know if this solved your issue.
