### ISSUE TITLE
app rejected by google play because of applovin sdk

### ISSUE THREAD

**Issue by Markieboyyy** [YoYoGames/GMEXT-AdMob#35]
![Screenshot 2024-02-28 231540](https://github.com/YoYoGames/GMEXT-AdMob/assets/130084256/5cc15c1b-2af4-479b-b101-1b6525210eff)

I have tried for almost 2 months now to publish my game, but everytime it got rejected. So I hope someone can help me here. I have asked in the gamemaker forum and in the discord and nobody knows how to fix this issue (look at the screenshot and the blue marking)

**Comment by KBeeeR** [comment]
Hello @Markieboyyy
I hope that you have already solved this issue. Here is my solution:
In app content / data safety, copy these choices:
Does your app collect or share any of the required user data types? Yes
Is all of the user data collected by your app encrypted in transit? Yes
Tick on "My app does not allow users to create an account."
Tick on "Device or other IDs."
