### ISSUE TITLE
Banner shows in top-left corner on iOS

### ISSUE THREAD

**Issue by KBeeeR** [YoYoGames/GMEXT-AdMob#36]
when i use AdMob_Banner_Create(AdMob_Banner_NORMAL,false);
On iOS, it shows the banner in the top-left corner instead of the top-center. 
The same project on Android shows the banner in the right place.

project info:
Extension version 1.3.3
IDE v2024.2.132 Runtime v2024.2.0.163
macOS Sonoma 14.4.1 - Xcode 15.3

**Comment by jzavala-YYG** [comment]
Hi @KBeeeR 

Can you include screenshots?
It happen with all the ads or with one specific ad?
It happen in the demo attached to the marketplace extension? 
it happen using test ads?

Regards

**Comment by KBeeeR** [comment]
it happen with all the ads? Yes
It happen in the demo attached to the marketplace extension? Yes
it happen using test ads? Yes

I tried with test ads, with my real ads, and with the Google test ad unit IDs that come with the extension.
By the way, AdMob_SetTestDeviceId() did not work on iOS; it shows real ads.

I tried landscape orientation and portrait.
I tried to remove all the mediation extensions.
and in all the situations, the banner shows in the left-top corner.
and when I went back to version 1.2.3 of the extension, the problem was solved.

![1](https://github.com/YoYoGames/GMEXT-AdMob/assets/140838901/7a37cf13-27e9-4040-9097-eb018c2ca3cc)

![2](https://github.com/YoYoGames/GMEXT-AdMob/assets/140838901/36d226d2-6102-49c1-9b43-8c4f6a6566e6)

![3](https://github.com/YoYoGames/GMEXT-AdMob/assets/140838901/9ef42e1f-131a-46a7-8f99-ab16ce10a7b3)

![4](https://github.com/YoYoGames/GMEXT-AdMob/assets/140838901/d30cb84f-a33a-474d-bd58-14834a60b802)

![5](https://github.com/YoYoGames/GMEXT-AdMob/assets/140838901/497182ed-ec9b-464a-b60f-eedb28583967)

**Comment by jzavala-YYG** [comment]
Thanks for the detailed report, Now it's fixed.

Issue appeared when a not SMART format banner was invoked.

**Comment by KBeeeR** [comment]
The problem isn't solved; I removed and reinstalled the extension v1.3.3 its not fixed.
btw im testing on iphone ios 17.4.1.

**Comment by jzavala-YYG** [comment]
@KBeeeR It's not on the marketplace yet. if you want early access to it you have to clone it from the repository.

**Comment by KBeeeR** [comment]
Ah that's clear. Thank you!
