### ISSUE TITLE
iOS Banner NORMAL-type Exchanges places

### ISSUE THREAD

**Issue by KBeeeR** [YoYoGames/GMEXT-AdMob#39]
Hello, I found an issue with version 1.3.5 on iOS.
with "AdMob_Banner_NORMAL" placement.

```
AdMob_Banner_Create(banner_type,false);
``` 
The apove code shows the banner at the bottom.

```
AdMob_Banner_Create(banner_type,true);
``` 

The apove code shows the banner at the top.

That issue happens in my project and in the demo attached to the Marketplace extension.
Please see the attached file. [Project_AdMob.zip](https://github.com/YoYoGames/GMEXT-AdMob/files/14895979/Project_AdMob.zip)

Project info:
- Extension version 1.3.5
- IDE v2024.2.132 Runtime v2024.2.0.163
- macOS Sonoma 14.4.1 - Xcode 15.3

Notes:
- I didn't test on real ads.
- In the attached project I didn't change anything but "Obj_AdMob_Banner"
- I couldn't find the manual file!

**Comment by DiasFranciscoA** [comment]
This is a known issues that is going to be fixed during the next week.

> [!NOTE]
> The new `GMEXT-AdMob Win Docs` or `GMEXT-AdMob Unix Docs` stored inside the datafiles folder will open the docs. Which are basically shortcuts to the actual docs inside the extension folder. You should use the one depending on your current OS. If you are no Windows use the `GMEXT-AdMob Win Docs` if you are on Unix (macOS or Linux) use `GMEXT-AdMob Unix Docs`

**Comment by jzavala-YYG** [comment]
789f840f9924bb45c9012c2ac1bfde02f2bf57fb
