### ISSUE TITLE
Documentation is forgotten in extension files for 1.3.5

### ISSUE THREAD

**Issue by Callsign54** [YoYoGames/GMEXT-AdMob#40]
It's in the AdMob extension folder. No need to bloat the gamesize 👍

**Comment by DiasFranciscoA** [comment]
That's exactly how the new documentation system works you can delete the old HTML docs from the datafile and use the new `GMEXT-AdMob Win Docs` or `GMEXT-AdMob Unix Docs` which are basically shortcuts to the actual docs inside the extension folder. 

> [NOTE]
> Files inside the extension folder are not copied to the compiled or build game you should not worry about that. Game size won't increase at all.

Francisco Dias
