### ISSUE TITLE
1.3.7 virus detect can't download

### ISSUE THREAD

**Issue by searoopy** [YoYoGames/GMEXT-AdMob#42]
1.3.7 virus detect can't download

**Comment by searoopy** [comment]
![image](https://github.com/YoYoGames/GMEXT-AdMob/assets/7219276/48f2aad2-10ac-4a7b-bb72-701cdde93e06)

**Comment by patrickrocheyoyo** [comment]
Hello, 

What was the name of the application that encountered this issue?

**Comment by DiasFranciscoA** [comment]
@searoopy, could you please test the (v1.3.8) and give us some feedback!
