### ISSUE TITLE
Ads don't work after a few viewings

### ISSUE THREAD

**Issue by searoopy** [YoYoGames/GMEXT-AdMob#44]
Users are reporting that ads are not showing up well

When the ad extension came to 1.3.3 from the previous 1.2.3 version, the
queue when the extension came to 1.3.3 from a previous version.

**Comment by searoopy** [comment]
Android, reward video

GuRis (game dev studio)
Lee sanghyun (ceo,dev)
homepage : Guris (webflow.io) <https://guris-game.webflow.io/>
mobile : +821032796789


2024년 4월 18일 (목) 오후 6:16, DiasFranciscoA ***@***.***>님이 작성:

**Comment by DiasFranciscoA** [comment]
The provided information is not enough for our team to replicate the issue. Please file a ticket in the helpdesk including the full project and the complete log. If file it directly from the IDE with the option Help-> file a bug the project is automatically include so we can analise it deeply.
