### ISSUE TITLE
This error happends when i put admob extension, since may 8th update

### ISSUE THREAD

**Issue by kerimyakamercan** [YoYoGames/GMEXT-AdMob#49]
Execution failed for task ':release.cubic.planet:generateDebugBuildConfig'.
> Error while evaluating property 'versionCode' of task ':release.cubic.planet:generateDebugBuildConfig'
   > Failed to calculate the value of task ':release.cubic.planet:generateDebugBuildConfig' property 'versionCode'.
      > org.xml.sax.SAXParseException; systemId: file:/C:/Users/mypc2/AppData/Roaming/GameMakerStudio2/Cache/GMS2CACHE/cubic_plan_5B457EBE_973B1148/android/Default/release.cubic.planet/src/main/AndroidManifest.xml; lineNumber: 17; columnNumber: 14; Element type "meta-data" must be followed by either attribute specifications, ">" or "/>".

**Comment by DiasFranciscoA** [comment]
What is the version of the IDE? Please go to `Settings -> Runtime -> Master` and make sure you are in the latest runner version 2024.4.1.xxx (there were runner updates fixing this error)

**Comment by DiasFranciscoA** [comment]
we will need a copy of the manifest file that has this problem,: 

`C:\Users\mypc2\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\cubic_plan_5B457EBE_973B1148\android\Default\release.cubic.planet\src\main\AndroidManifest.xml`

Also are you able to run the AdMob extension demo project provided with the extension if you are able to run it then this is an integration problem and not a extension problem. Please also make sure you clean the build from the IDE before attempting a new build as some files can be kept in cache and create problems
