### ISSUE TITLE
iOS onPaidEventHandler wrong micros value!

### ISSUE THREAD

**Issue by romhaviv** [YoYoGames/GMEXT-AdMob#53]
we should change 
dsMapAddDouble(dsMapIndex, (char*)"micros", value.value.doubleValue);

to 

dsMapAddDouble(dsMapIndex, (char*)"micros", value.value.doubleValue * 1000000.0);

because in iOS, unlike in android, the value is not in micros. therefore, needs to be multiplied to become micros.

**Comment by jzavala-YYG** [comment]
@romhaviv thanks for reporting!
