### ISSUE TITLE
AdMob and Foreground Service Permission

### ISSUE THREAD

**Issue by mcellis89** [YoYoGames/GMEXT-AdMob#57]
The admob extension appears to be requesting a foreground service permission.

As far as I can tell from google's recent policy update, for apps that target android 14 and request foreground service permissions developers have to fill out a form in play console explaining why their app is requesting the permission and provide a video demonstrating their app using the foreground service.

I analyzed an apk of an otherwise empty gamemaker project that just contains the admob exension v1.3.10 on this website https://sisik.eu/apk-tool and got the following information.

-REQUESTED PERMISSIONS
android.permission.INTERNET
com.google.android.gms.permission.AD_ID
android.permission.ACCESS_NETWORK_STATE
android.permission.ACCESS_ADSERVICES_AD_ID
android.permission.ACCESS_ADSERVICES_ATTRIBUTION
android.permission.ACCESS_ADSERVICES_TOPICS
android.permission.WAKE_LOCK
android.permission.FOREGROUND_SERVICE
com.company.game.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION

-ACTIVITIES
com.company.game.RunnerActivity
com.google.android.gms.ads.AdActivity com.google.android.gms.ads.OutOfContextTestingActivity com.google.android.gms.ads.NotificationHandlerActivity com.google.android.gms.common.api.GoogleApiActivity

-SERVICES
com.google.android.gms.ads.AdService
androidx.work.impl.background.systemalarm.SystemAlarmService androidx.work.impl.background.systemjob.SystemJobService androidx.work.impl.foreground.SystemForegroundService androidx.room.MultiInstanceInvalidationService

-BROADCAST RECEIVERS
androidx.work.impl.utils.ForceStopRunnable$BroadcastReceiver
androidx.work.impl.background.systemalarm.ConstraintProxy$BatteryChargingProxy androidx.work.impl.background.systemalarm.ConstraintProxy$BatteryNotLowProxy androidx.work.impl.background.systemalarm.ConstraintProxy$StorageNotLowProxy androidx.work.impl.background.systemalarm.ConstraintProxy$NetworkStateProxy androidx.work.impl.background.systemalarm.RescheduleReceiver androidx.work.impl.background.systemalarm.ConstraintProxyUpdateReceiver androidx.work.impl.diagnostics.DiagnosticsReceiver

-CONTENT PROVIDERS
com.google.android.gms.ads.MobileAdsInitProvider
androidx.startup.InitializationProvider

The requested foreground service permission dosen't specify a type as required by google play
and I don't know how I would go about filling out the form or what kind of video to make since I don't really know how or why admob uses this permission.

I'm thinking maybe the foreground service permission doesn't count because maybe it's related to work manager, in the play academy course on foreground services it mentions using work manager instead of foreground services.

This part "androidx.work.impl.foreground.SystemForegroundService" from the above list of services also makes me think that maybe it doesn't count but I'm not sure, that's why I'm asking those who made the extension for more information, thank you.

**Comment by jzavala-YYG** [comment]
@mcellis89 can you link me to the policy update? and Google it's already requesting you the video?

And thanks for the link of the APK analyzer, will be really useful in the future.

Regards

**Comment by mcellis89** [comment]
@jzavala-YYG I haven't updated to android 14 yet so Google hasn't asked for a form declaration or video.
I'm glad you find the APK analyzer useful!

Link to Google Policy
https://support.google.com/googleplay/android-developer/answer/13392821?sjid=1455588707729128180-NC

Thank you.

**Comment by jzavala-YYG** [comment]
Thanks for the link, at the moment I don't found something to do related to PlayStore, Admob and foreground service, I will keep this ticket open until confirm if we need take action on this.

**Comment by mcellis89** [comment]
Thank you to everyone for attending to this issue.

Since the deadline regarding Foreground Service Permissions was August-31-2024, I had updated my apps to target Android 14 without the AdMob extension in order to meet that deadline.

I would like to add AdMob back to may apps again but the APK of an otherwise blank project using the extension v1.4.5 still shows that it requests 

android.permission.FOREGROUND_SERVICE 

and uses

androidx.work.impl.foreground.SystemForegroundService

Has anyone been able to confirm if the play console asks for a form declaration and example video for apps using the AdMob extension?

**Comment by mcellis89** [comment]
I have confirmed that play console does not ask for a form declaration or example video.
