### ISSUE TITLE
No LTS support

### ISSUE THREAD

**Issue by harpwood** [YoYoGames/GMEXT-AdMob#58]
Please add a branch/release with an updated version of the admob extension that is compatible with the LTS version of the gamemaker

**Comment by DiasFranciscoA** [comment]
@harpwood The current release should be compatible with LTS as it is tested to work there. Could you please be more specific on what is the issue you are encountering?

**Comment by DiasFranciscoA** [comment]
The problem was in the LTS imported not the extension this should be now fixed and working fine in a future LTS release (update).
