### ISSUE TITLE
Support for changes app orientaion

### ISSUE THREAD

**Issue by shaharOssy** [YoYoGames/GMEXT-AdMob#59]
My app supports multi-orienation,
the user can rotate many times the app.
half of the time the interstitials and openAd are shown in the incorrect orientation, causing screen to change and deform.
It doesnt make sense to request a new add each time the user rotate the screen.

Interstitials should have control over that, for example let me load 2 ads, one portrait and one landscape, then show the correct one based on the device current orrientation.

openAd should, for example, detect if its orientation does not match the app's orientation on resume, and not show ad in that case.

There may be other solutions.. these things are REALLY anoying to user, seeing ads not correctly. 

Any other advice will help.

**Comment by jzavala-YYG** [comment]
@shaharOssy 
We already implemented a solution for this issue on the repository, soon should reach the marketplace.

Basically it's call forget and load again the ads.
```
if(orientation != display_get_orientation())
{
	show_debug_message("[AdMob] Orientation Changed!!!!")
	
	orientation = display_get_orientation()
	
	var Interstitial_Instances_Count = AdMob_Interstitial_Instances_Count()
	Admob_Interstitial_Free_Loaded_Instances(Interstitial_Instances_Count)
	repeat(Interstitial_Instances_Count)
		AdMob_Interstitial_Load()
	
	var RewardedInterstitial_Instances_Count = AdMob_RewardedInterstitial_Instances_Count()
	AdMob_RewardedInterstitial_Free_Loaded_Instances(Interstitial_Instances_Count)
	repeat(Interstitial_Instances_Count)
		AdMob_RewardedInterstitial_Load()
	
	var RewardedVideo_Instances_Count = AdMob_RewardedVideo_Instances_Count()
	AdMob_RewardedVideo_Free_Loaded_Instances(Interstitial_Instances_Count)
	repeat(Interstitial_Instances_Count)
		AdMob_RewardedVideo_Load()
		
	AdMob_AppOpenAd_Disable()
	
	switch(orientation)
	{
		case display_landscape:
		case display_landscape_flipped:
			AdMob_AppOpenAd_Enable(display_landscape)
		break
		
		case display_portrait:
		case display_portrait_flipped:
			AdMob_AppOpenAd_Enable(display_portrait)
		break
	}
}

```

**Comment by shaharOssy** [comment]
Thank you but this solution not good enough. 

Reloading new ad every time screen rotates is really bad behavior.

For example, The app starts on menu in portrait mode. then the user starts a new game in landscape mode.
In this method I must request a new ad.
The game starts, and the ad is coming interfering the game making the game characters movement lag for 3-5 seconds.

Now, I want to be able to request a landscape-interstitial-ad while i'm in portrait-orientation. Just like it is possible with openAd. 

Is it possible?

**Comment by jzavala-YYG** [comment]
Hi @shaharOssy I'm sorry but it's not possible, we can't request the interstitial orientation.
