### ISSUE TITLE
Android ANR after update to version 1.4.0 and 1.4.1

### ISSUE THREAD

**Issue by alikarim0089** [YoYoGames/GMEXT-AdMob#68]
Hi sir have a nice day
I get google play report about increase ANRs after i update my app on google play
after i test my app i get this debug report on android
this happen with latest GameMaker stable version and Beta

target sdk : 35
min sdk :21
compile sdk 35;
sdk build number : 34.0.0
with ndk 27.0.12077973

--------- beginning of crash
10-01 16:04:21.584 15143 15143 E AndroidRuntime: FATAL EXCEPTION: main
10-01 16:04:21.584 15143 15143 E AndroidRuntime: Process: com.smg.rt, PID: 15143
10-01 16:04:21.584 15143 15143 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.relevantech.cap.CapApplication: java.lang.IllegalStateException: Apps may not schedule more than 100 distinct jobs
10-01 16:04:21.584 15143 15143 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7598)
10-01 16:04:21.584 15143 15143 E AndroidRuntime: 	at android.app.ActivityThread.access$1500(ActivityThread.java:301)
10-01 16:04:21.584 15143 15143 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2177)
10-01 16:04:21.584 15143 15143 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-01 16:04:21.584 15143 15143 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:246)
10-01 16:04:21.584 15143 15143 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8653)
10-01 16:04:21.584 15143 15143 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-01 16:04:21.584 15143 15143 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
10-01 16:04:21.584 15143 15143 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
10-01 16:04:21.584 15143 15143 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Apps may not schedule more than 100 distinct jobs
10-01 16:04:21.584 15143 15143 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2394)
10-01 16:04:21.584 15143 15143 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2370)
10-01 16:04:21.584 15143 15143 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2353)
10-01 16:04:21.584 15143 15143 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2295)
10-01 16:04:21.584 15143 15143 E AndroidRuntime: 	at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:308)
10-01 16:04:21.584 15143 15143 E AndroidRuntime: 	at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:47)
10-01 16:04:21.584 15143 15143 E AndroidRuntime: 	at com.relevantech.cap.jobs.CheckAdsQueueJobService.schedule(CheckAdsQueueJobService.java:77)
10-01 16:04:21.584 15143 15143 E AndroidRuntime: 	at com.relevantech.cap.campaign.AdsQueue.startExecutionQueue(AdsQueue.java:425)
10-01 16:04:21.584 15143 15143 E AndroidRuntime: 	at com.relevantech.cap.campaign.AdsQueue.<init>(AdsQueue.java:63)
10-01 16:04:21.584 15143 15143 E AndroidRuntime: 	at com.relevantech.cap.campaign.AdsQueue.init(AdsQueue.java:68)
10-01 16:04:21.584 15143 15143 E AndroidRuntime: 	at com.relevantech.cap.campaign.CampaignMonitor.init(CampaignMonitor.java:27)
10-01 16:04:21.584 15143 15143 E AndroidRuntime: 	at com.relevantech.cap.CapClient.<init>(CapClient.java:127)
10-01 16:04:21.584 15143 15143 E AndroidRuntime: 	at com.relevantech.cap.CapClient.init(CapClient.java:282)
10-01 16:04:21.584 15143 15143 E AndroidRuntime: 	at com.relevantech.cap.CapApplication.onCreate(CapApplication.java:41)
10-01 16:04:21.584 15143 15143 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
10-01 16:04:21.584 15143 15143 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7593)
10-01 16:04:21.584 15143 15143 E AndroidRuntime: 	... 8 more
10-01 16:04:21.584 15143 15143 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
10-01 16:04:21.584 15143 15143 E AndroidRuntime: 	at com.android.server.job.JobSchedulerService.scheduleAsPackage(JobSchedulerService.java:1102)
10-01 16:04:21.584 15143 15143 E AndroidRuntime: 	at com.android.server.job.JobSchedulerService$JobSchedulerStub.schedule(JobSchedulerService.java:2657)
10-01 16:04:21.584 15143 15143 E AndroidRuntime: 	at android.app.job.IJobScheduler$Stub.onTransact(IJobScheduler.java:153)
10-01 16:04:21.584 15143 15143 E AndroidRuntime: 	at android.os.Binder.execTransactInternal(Binder.java:1190)
10-01 16:04:21.584 15143 15143 E AndroidRuntime: 	at android.os.Binder.execTransact(Binder.java:1159)
10-01 16:04:21.584 15143 15143 E AndroidRuntime: 
10-01 16:04:21.587 15143 15143 I AndroidRuntime: VM exiting with result code 1, cleanup skipped.

**Comment by DiasFranciscoA** [comment]
From the error log the problem seems to be related to a `com.relevantech.cap.CapApplication` import and not directly related to the AdMob extension are there any other extensions being used in your project? can you do a search on the extensions to see if any of them is using the `com.relevantech.cap.CapApplication` import?

**Comment by alikarim0089** [comment]
Thank you for replay i solved this ANR in my audio service extension
